// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcrwuzjfigmvpwrxzveo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcnd1empmaWdtdnB3cnh6dmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzcyOTEsImV4cCI6MjA2MTk1MzI5MX0.rRTPpG24rZ9wkwETSK3MCup7S2-rztWWCaLh2oLWPv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);